summarize_task:
  description: >
    Resuma o seguinte texto 
    {textToSummarize}
  expected_output: >
    Um texto em Português do Brasil
  agent: writer

summarize_paragraph_task:
  description: >
    Resume para apenas um parágrafo o conteúdo recebido como contexto.
  expected_output: >
    Um texto em Português do Brasil com apenas um parágrafo.
  agent: writerparagraph

summarize_phrases_task:
  description: >
    Resume para apenas 3 frases o conteúdo recebido como contexto. Sendo uma frase de no máximo 20 palavras para cada evento principal e mais grave do texto.
  expected_output: >
    Um texto em Português do Brasil com apenas 3 frases.
  agent: writereventtopic
