scrape_configs:
  - job_name: "spark-worker-1"
    static_configs:
      - targets: ["spark-worker-1:7072"]

  - job_name: "spark-worker-2"
    static_configs:
      - targets: ["spark-worker-2:7073"]

  - job_name: "spark-history"
    static_configs:
      - targets: ["spark-history:7074"]
